---
apiVersion: v1
kind: Service
metadata:
  annotations:
    derrick.service.type: nodeport
    derrick.version: 0.0.14
  labels:
    derrick.service: springbootstrap
  name: springbootstrap
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    derrick.service: springbootstrap
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    derrick.version: 0.0.14
  labels:
    derrick.service: springbootstrap
  name: springbootstrap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        derrick.service: springbootstrap
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/jingshan/springbootstrap
        name: web
        ports:
        - containerPort: 8080