apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    derrick.version: 0.0.14
  labels:
    derrick.service: springbootstrap
  name: springbootstrap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        derrick.service: springbootstrap
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/jingshan/springbootstrap:latest
        name: web
        ports:
        - containerPort: 8080